stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    params:
    - make_dataset.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/processed
    - data/raw
    - src/features/build_features.py
    params:
      - build_features.max_features
    outs:
    - data/feature
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed
    - data/raw
    - src/features/build_features.py
    - src/models/model_building.py
    params:
    - model_building.n_estimators 
    - model_building.learning_rate 
    outs:
    - model.pkl
  model_evalv:
    cmd: python src/models/model_evalv.py
    deps:
    - model.pkl
    - src/models/model_evalv.py
    metrics:
    - metrics.json

